version: 2.1

vars: &globals
  IMAGE_NAME: boxheed/supercronic
  SUPERCRONIC_VERSION: 0.2.24
  SUPERCRONIC_CHECKSUM: 6817299e04457e5d6ec4809c72ee13a43e95ba41

jobs:
  build:
    docker:
      - image: docker:24.0.2-git
    working_directory: ~/repo
    environment: *globals
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/cache.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/cache.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build \
              --build-arg SUPERCRONIC_VERSION=$SUPERCRONIC_VERSION \
              --build-arg SUPERCRONIC_CHECKSUM=$SUPERCRONIC_CHECKSUM \
              --cache-from=$IMAGE_NAME:$SUPERCRONIC_VERSION \
              -t $IMAGE_NAME:$SUPERCRONIC_VERSION \
              .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/cache.tar $IMAGE_NAME:$SUPERCRONIC_VERSION
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/cache.tar

  release:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install autotag
          command: curl -sL https://git.io/autotag-install | sh --
      - run:
          name: increment version
          command: ./bin/autotag
      - run: 
          name: push tags
          command: git push --tags

  publish:
    docker:
      - image: docker:24.0.2-git
    working_directory: ~/repo
    environment: *globals
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build \
              --build-arg SUPERCRONIC_VERSION=$SUPERCRONIC_VERSION \
              --build-arg SUPERCRONIC_CHECKSUM=$SUPERCRONIC_CHECKSUM \
              -t $IMAGE_NAME:$SUPERCRONIC_VERSION \
              -t $IMAGE_NAME:$SUPERCRONIC_VERSION-$CIRCLE_TAG \
              -t $IMAGE_NAME:latest \
              .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME -a

workflows:
  build:
    jobs:
      - build:
          context: boxhead-builds
      - release:
          context: boxhead-builds
          requires: 
            - build
          filters:
            branches:
              only: /^(?:main|master)$/
      - publish:
          context: boxhead-builds
          filters:
            # only act on version tags
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/