version: 2.1

jobs:
  build:
    working_directory: /app
    environment:
      IMAGE_NAME: boxheed/supercronic
      SUPERCRONIC_VERSION: 0.2.0
    docker:
      - image: docker:24.0.2-git
    steps:
      - checkout
      - setup_remote_docker
#      - run:
#          name: Install dependencies
#          command: |
#            apk add --no-cache \
#              py-pip=9.0.0-r1
#            pip install \
#              docker-compose==1.12.0 
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/image_cache.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --build-arg SUPERCRONIC_VERSION=$SUPERCRONIC_VERSION --cache-from=app -t $IMAGE_NAME:$SUPERCRONIC_VERSION -t $IMAGE_NAME:latest .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/image_cache.tar $IMAGE_NAME:latest
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/image_cache.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME -a

workflows:
  build:
    jobs:
      - build:
          context: boxhead-builds
          filters:
            branches:
              only: /^(?:main|master)$/